/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package actionPerformedGUI;

import edu.memphis.ccrg.lida.framework.ModuleName;
import edu.memphis.ccrg.lida.framework.gui.panels.GuiPanelImpl;
import java.util.logging.Level;
import modules.Environment;

/**
 *
 * @author ra171941
 */
public class ActionPerformedGUI extends GuiPanelImpl {

    /**
     * Creates new form ActionPerformedGUI
     */
    
    Environment environment;
    
    public ActionPerformedGUI() {
        
        initComponents();
    }
    
    @Override
    public void initPanel(String[] args){
        environment = (Environment) agent.getSubmodule(ModuleName.Environment);
        if (environment != null) {
            System.out.println("certo");
            refresh();
        } else {
            System.out.println("EROR");
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        action = new javax.swing.JLabel();

        action.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        action.setText("ACTION");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addComponent(action, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(83, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addComponent(action, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(66, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
    
    
    @Override
    public void refresh()
    {
        action.setText(environment.getCommand());
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel action;
    // End of variables declaration//GEN-END:variables
}
